### ISSUE TITLE
Reference

### ISSUE THREAD

**Issue by leewujung** [raimon-fa/palm-nmf#1]
This is very useful! Could you please point me to a reference of the formulation? Thanks!

**Comment by raimon-fa** [comment]
Hi. I am glad you found this useful. I uploaded a pdf file with the description of the method and references. We didn't publish the algorithm yet, (and we are not sure we will), so I'm not sure how can you cite it. I'd be glad to know if this algorithm was helpful to you and how, to know if it is worth publishing it.
Best,
Raimon

**Comment by leewujung** [comment]
Awesome, thank you so much! We are looking at the temporal continuity part at the moment, and may end up changing the cost function due to the large dynamic range of data. But we will definitely keep you posted!

**Comment by raimon-fa** [comment]
Cool thanks!

**Comment by valentina-s** [comment]
I work with @leewujung and started implementing a Python version of the algorithm:

https://github.com/valentina-s/smoothNMF

Have you published your work somewhere, we are happy to link to it and cite it. If not you can consider uploading to some preprint server such as arXiv. Also, if you can add a license to your code then other people would know how to reuse it, share it, and refer to it properly. Many open source software projects use a BSD or MIT License, you can use this website to decide https://choosealicense.com/. Thanks!

**Comment by raimon-fa** [comment]
Hi! Thanks for your support. I haven't published this anywhere and i did not plan to. If I have time the following weeks ill try to submit something to arXiv so you can cite it and add a proper license to the code. Don't hesitate to ask anything else!

**Comment by leewujung** [comment]
Hello @raimon-fa! @valentina-s and I wanted to ask if you could upload your manuscript to arXiv, so that we can cite it properly in a ms we are going to submit (hopefully!) in this coming month. We also wanted to let you know that https://github.com/valentina-s/ss-nmf has the latest Python implementation of the algorithm.
